name: 'Fetch Postman Collection'
description: 'Fetch a Postman collection and save it as a JSON file.'
author: 'Your Name'
inputs:
  postman_collection_id:
    description: 'The Postman collection ID to fetch.'
    required: true
  postman_api_key:
    description: 'Your Postman API key.'
    required: true
  output_file:
    description: 'The file where the Postman collection will be saved.'
    required: false
    default: 'collection.json'

outputs:
  saved_file:
    value: ${{ inputs.output_file }}
    description: 'The path to the saved file.'

runs:
  using: 'composite'
  steps:
    - name: Fetch Postman Collection
      shell: bash
      run: |
        curl -s -H "X-API-Key: ${{ inputs.postman_api_key }}" \
          "https://api.postman.com/collections/${{ inputs.postman_collection_id }}" \
          | jq '.collection' > ${{ inputs.output_file }}
        echo "saved_file=${{ inputs.output_file }}" >> $GITHUB_OUTPUT

    - name: Validate JSON
      shell: bash
      run: |
        jq empty ${{ inputs.output_file }} || (echo "Invalid JSON file" && exit 1)
