name: API Spec Fetch and Sync

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  fetch_postman_collection:
    runs-on: ubuntu-latest

    permissions:
      contents: write # This grants write access to the repository contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Call Fetch Postman Collection Action
        uses: ./.github/actions/fetch-postman-collection-action
        with:
          postman_collection_id: ${{ secrets.POSTMAN_COLLECTION_ID }}
          postman_api_key: ${{ secrets.POSTMAN_API_KEY }}
          output_file: 'postman-collection.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
